#!/bin/bash

# If any command fails, the script will exit immediately
set -o errexit
# If any command in a pipeline fails, the script will exit immediately
set -o pipefail
# If any variable is used but not set, the script will exit immediately
set -o nounset

postgres_ready() {
python << END
import sys

import psycopg2
import urllib.parse as urlparse
import os

url = urlparse.urlparse(os.environ["DATABASE_URL"])
dbname = url.path[1:]
user = url.username
password = url.password
host = url.hostname
port = url.port

try:
    psycopg2.connect(
        dbname=dbname,
        user=user,
        password=password,
        host=host,
        port=port
    )
except psycopg2.OperationalError as e:
    sys.exit(-1)
sys.exit(0)

END
}
until postgres_ready; do
    >&2 echo "Waiting for PostgreSQL to be ready..."
    sleep 1
done
>&2 echo "PostgreSQL is ready, starting FastAPI server..."

exec "$@"