# filepath: .github/workflows/security.yml
name: Security Scan

on: [push, pull_request]

jobs:
  code_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install bandit semgrep safety pip-audit detect-secrets

      - name: Bandit scan (warn only)
        run: bandit -r project/
        continue-on-error: true

      - name: Semgrep OWASP scan (warn only)
        run: semgrep --config=p/owasp project/
        continue-on-error: true

      - name: Safety dependency check
        run: safety check

      - name: Pip-audit
        run: pip-audit

      - name: Detect secrets baseline
        run: |
          detect-secrets scan > new.baseline
          diff .secrets.baseline new.baseline || echo "Secrets changed!"

  container_scan:
    runs-on: ubuntu-latest
    needs: code_scan
    steps:
      - uses: actions/checkout@v4

      - name: Install Trivy
        run: |
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
            | sudo sh -s -- -b /usr/local/bin

      - name: Build image
        run: docker build -t project-web:latest ./

      - name: Scan image (warn only)
        run: trivy image project-web:latest
        continue-on-error: true