# filepath: .github/workflows/security.yml
name: Security Scan

on: [push, pull_request]

jobs:
  code_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install bandit semgrep safety pip-audit detect-secrets

      - name: Bandit scan
        run: bandit -r project/ 

      - name: Semgrep OWASP scan
        run: semgrep --config=p/owasp project/

      - name: Safety dependency check
        run: safety check

      - name: Pip-audit
        run: pip-audit

      - name: Detect secrets baseline
        run: |
          detect-secrets scan > new.baseline
          diff .secrets.baseline new.baseline || echo "Secrets changed!"

  container_scan:
    runs-on: ubuntu-latest
    needs: code_scan
    steps:
      - uses: actions/checkout@v4
      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_$(uname -s)_$(uname -m).tar.gz \
            && tar zxvf trivy_* && sudo mv trivy /usr/local/bin/
      - name: Build image
        run: docker build -t project-web:latest ./ 
      - name: Scan image
        run: trivy image project-web:latest